sudo: required
services:
  - docker

before_install:
  - docker build -t kaiserdocker22/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kaiserdocker22/docker-react npm run test -- --coverage

language: generic 
