sudo: required
services:
  - docker

before_install:
  - docker build -t kaiserdocker22/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kaiserdocker22/docker-react npm run test -- --coverage

language: generic 

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "docker"
  bucket_path: "s3://elasticbeanstalk-us-east-2-042043866569/resources/_runtime/_embedded_extensions/docker/eabeea04dad342a5a182a4d61e99fb2d"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
on:
  branch:master



  